#!/usr/bin/env bash
# Simple launcher — inherits the calling shell's environment.
# Generated by global-meta. Placeholders:
#   <RT>   runtime token: claude | codex
#   <VAR>  config-home env var: CLAUDE_CONFIG_DIR | CODEX_HOME
#   <BIN>  exec binary: claude | codex
#   <name> profile name
export <VAR>="$HOME/.<RT>-<name>"
if [ -f "$HOME/.config/<RT>-<name>/env" ]; then
  source "$HOME/.config/<RT>-<name>/env"
fi
exec <BIN> "$@"
