#!/usr/bin/env bash
# Isolated launcher — unsets common API/token env vars before launching.
# Use for work/client profiles to prevent env-var leakage from the parent shell.
# Generated by global-meta. Placeholders:
#   <RT>   runtime token: claude | codex
#   <VAR>  config-home env var: CLAUDE_CONFIG_DIR | CODEX_HOME
#   <BIN>  exec binary: claude | codex
#   <name> profile name
#   <EXTRA_UNSET>  codex: replace with `unset OPENAI_API_KEY`; claude: delete this line
export <VAR>="$HOME/.<RT>-<name>"
unset ANTHROPIC_API_KEY ANTHROPIC_AUTH_TOKEN ANTHROPIC_BASE_URL
<EXTRA_UNSET>
unset GITHUB_TOKEN GOOGLE_APPLICATION_CREDENTIALS
unset SLACK_BOT_TOKEN LINEAR_API_KEY JIRA_API_TOKEN CONFLUENCE_API_TOKEN
if [ -f "$HOME/.config/<RT>-<name>/env" ]; then
  source "$HOME/.config/<RT>-<name>/env"
fi
exec <BIN> "$@"
