#!/usr/bin/env bash
# Isolated launcher — unsets common API/token env vars before launching.
# Use for work or client profiles to prevent env-var leakage from parent shell.
# Generated by profile-creator. Replace <name> with the profile name.
export CLAUDE_CONFIG_DIR="$HOME/.claude-<name>"
unset ANTHROPIC_API_KEY ANTHROPIC_AUTH_TOKEN ANTHROPIC_BASE_URL
unset GITHUB_TOKEN GOOGLE_APPLICATION_CREDENTIALS
unset SLACK_BOT_TOKEN LINEAR_API_KEY JIRA_API_TOKEN CONFLUENCE_API_TOKEN
if [ -f "$HOME/.config/claude-<name>/env" ]; then
  source "$HOME/.config/claude-<name>/env"
fi
exec claude "$@"
