#!/usr/bin/env bash
# Simple launcher — inherits the calling shell's environment.
# Generated by profile-creator. Replace <name> with the profile name.
export CLAUDE_CONFIG_DIR="$HOME/.claude-<name>"
if [ -f "$HOME/.config/claude-<name>/env" ]; then
  source "$HOME/.config/claude-<name>/env"
fi
exec claude "$@"
